name: Terragrunt Plan

on:
  push:
    branches:
      - main
    paths:
      - 'scripts/iac/**'

jobs:
  terragrunt:
    name: Terragrunt
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    
    defaults:
      run:
        working-directory: ./scripts/iac

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Setup Terragrunt
      uses: autero1/action-terragrunt@v1.1.0
      with:
        terragrunt_version: 'v0.86.2'

    - name: Terragrunt Init
      run: terragrunt init

    - name: Terragrunt Plan
      run: terragrunt plan
